version: '3.8'

networks:
    nuxt:
      driver: bridge

services:
  mysql:
    image: mysql/mysql-server
    ports:
      - 3306:3306
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_DATABASE=mysql_db
    networks:
      - nuxt
  server:
    container_name: app
    restart: always
    build:
      context: server/.
    ports:
      - 3333:3333
    env_file:
      - server/.env
    networks:
      - nuxt

  client:
    container_name: client
    restart: always
    build:
      context: client/.
    ports:
      - 3000:3000
    networks:
      - nuxt

